package com.pojo;

// Generated Mar 26, 2018 8:51:19 AM by Hibernate Tools 3.4.0.CR1

/**
 * Firrecord generated by hbm2java
 */
public class Firrecord implements java.io.Serializable {

	private Integer firNo;
	private Registration registration;
	private String victimName;
	private String victimAddress;
	private String information;

	public Firrecord() {
	}

	public Firrecord(Registration registration, String victimName, String victimAddress, String information) {
		this.registration = registration;
		this.victimName = victimName;
		this.victimAddress = victimAddress;
		this.information = information;
	}

	public Integer getFirNo() {
		return this.firNo;
	}

	public void setFirNo(Integer firNo) {
		this.firNo = firNo;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getVictimName() {
		return this.victimName;
	}

	public void setVictimName(String victimName) {
		this.victimName = victimName;
	}

	public String getVictimAddress() {
		return this.victimAddress;
	}

	public void setVictimAddress(String victimAddress) {
		this.victimAddress = victimAddress;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

}
