package com.pojo;

// Generated Mar 26, 2018 8:51:19 AM by Hibernate Tools 3.4.0.CR1

/**
 * Missingrecord generated by hbm2java
 */
public class Missingrecord implements java.io.Serializable {

	private Integer missingNo;
	private Registration registration;
	private String missingthing;
	private String missingthingaddress;
	private String information;

	public Missingrecord() {
	}

	public Missingrecord(Registration registration, String missingthing, String missingthingaddress, String information) {
		this.registration = registration;
		this.missingthing = missingthing;
		this.missingthingaddress = missingthingaddress;
		this.information = information;
	}

	public Integer getMissingNo() {
		return this.missingNo;
	}

	public void setMissingNo(Integer missingNo) {
		this.missingNo = missingNo;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getMissingthing() {
		return this.missingthing;
	}

	public void setMissingthing(String missingthing) {
		this.missingthing = missingthing;
	}

	public String getMissingthingaddress() {
		return this.missingthingaddress;
	}

	public void setMissingthingaddress(String missingthingaddress) {
		this.missingthingaddress = missingthingaddress;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

}
