package com.pojo;

// Generated Mar 26, 2018 8:51:19 AM by Hibernate Tools 3.4.0.CR1

/**
 * Theftrecord generated by hbm2java
 */
public class Theftrecord implements java.io.Serializable {

	private Integer theftNo;
	private Registration registration;
	private String theftthing;
	private String theftthingaddress;
	private String information;

	public Theftrecord() {
	}

	public Theftrecord(Registration registration, String theftthing, String theftthingaddress, String information) {
		this.registration = registration;
		this.theftthing = theftthing;
		this.theftthingaddress = theftthingaddress;
		this.information = information;
	}

	public Integer getTheftNo() {
		return this.theftNo;
	}

	public void setTheftNo(Integer theftNo) {
		this.theftNo = theftNo;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getTheftthing() {
		return this.theftthing;
	}

	public void setTheftthing(String theftthing) {
		this.theftthing = theftthing;
	}

	public String getTheftthingaddress() {
		return this.theftthingaddress;
	}

	public void setTheftthingaddress(String theftthingaddress) {
		this.theftthingaddress = theftthingaddress;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

}
